version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: task_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  localstack:
    image: localstack/localstack
    ports:
    - "4566:4566"
    environment:
    - SERVICES=s3
    - DEFAULT_REGION=us-east-1
    - DEBUG=1
    volumes:
    - "./.localstack:/var/lib/localstack"
    - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mongodata: